### PR TITLE
REFACTOR: Move common Auth logic to a service

### LINKED ISSUE #24: Refactor auth controllers to re-use more logic
`local.auth.controller.ts`, `google.auth.controller.ts` and `github.auth.controller.ts` have very similar code. We should create some sort of auth service, which will have more generic methods for getting/creating users, signing tokens, checking the state cookie, etc.

Tracking:
- [x] #6

### PR DESCRIPTION
**Pull request by Daste745**
The service is constructed as an Elysia plugin, so it can facilitate dependency injection and register needed errors.
It's available under `authService` on the Context object.

Closes #24

### CODE REVIEW

**Review by HKGx — APPROVED** [review]
I'm really happy with how this turned out :+1:
My only question is that, does `authService` bleed into other routes?

**Comment by Daste745** [comment]
Unfortunately, yes. The service is accessible in `auth.controller.ts`:
```ts
export default new Elysia({ prefix: "/auth" })
  .use(userModel)
  .use(localAuth)
  .use(githubAuth)
  .use(googleAuth)
  .get("/test", ({ authService }) => (authService.signToken({userId: "foo", username: "bar"})))
  .use(authMiddleware)
  .get("/me", ({ user }) => user, {
    response: "user.user",
    detail: schemaDetail,
  });
```
```sh
$ http -b get :8080/api/auth/test
eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImZvbyIsInN1YiI6ImJhciIsImV4cCI6MTY5ODE0MTg2OX0.ojbnXK3EBqqaOkE4V3nfICxaOXPu4IAQCpxe68MvjfU
```

Using `scoped: true` on local, github and google auth controllers gets rid of this issue:
image

Unfortunately, this also removes registered errors, so we'd have to re-declare them on a higher level. Only `UnauthorizedError` survided, because it's registered in the un-scoped `authMiddleware`.
image

**Comment by Daste745** [comment]
I don't think we need to stress this too much. We'd need a way of granularly picking which registered components we want to scope.

**Comment by HKGx** [comment]
OK, cool, LGTM then
🚀

**Pull request merged**
